DECLARE
	AGE NUMBER(3);
	NOT_ALIGIBLE EXCEPTION;
BEGIN
	AGE := &AGE;
	IF AGE >=16 THEN
	
	DBMS_OUTPUT.PUT_LINE('YOU ALIGIBLE FOR 	LEARNING LICENCE');
	ELSE
	RAISE NOT_ALIGIBLE ;
	END IF ;
EXCEPTION
	WHEN NOT_ALIGIBLE THEN
	DBMS_OUTPUT.PUT_LINE('YOU NOT ALIGIBLE FOR LEARNING LICENCE');
END ;
/